import { PixelAvatar } from "@/app/components/pixel-avatar";

// Visual placeholder for stories: black-and-white film frames, generated by
// scripts/seed-demo.ts. Real stories arrive with the photo booth.
const DEMO_STORIES = [
  { username: "wave_rider", image: "/demo/stories/story-1.png" },
  { username: "moon_pixel", image: "/demo/stories/story-2.png" },
  { username: "film_fern", image: "/demo/stories/story-3.png" },
  { username: "star_gazer99", image: "/demo/stories/story-4.png" },
  { username: "cloud_kid", image: "/demo/stories/story-5.png" },
  { username: "retro_rin", image: "/demo/stories/story-6.png" },
];

export function StoriesRow({ myUsername }: { myUsername: string }) {
  return (
    <section aria-label="Stories" className="pixel-card mb-8 px-4 py-3">
      <div className="no-scrollbar flex items-start gap-4 overflow-x-auto">
        <div className="flex w-16 flex-col items-center gap-1">
          <div className="relative">
            <span className="story-ring block bg-blue-pale p-1">
              <PixelAvatar username={myUsername} size={48} className="border-0" />
            </span>
            <span
              className="font-pixel absolute -bottom-1 -right-1 grid h-5 w-5 place-items-center rounded-md border-2 border-[var(--blue-deep)] bg-yellow-brand text-[0.6rem] text-blue-deep"
              aria-hidden
            >
              +
            </span>
          </div>
          <span className="w-full truncate text-center text-base text-blue-deep">you</span>
        </div>
        {DEMO_STORIES.map((story) => (
          <div key={story.username} className="flex w-16 flex-col items-center gap-1">
            <span className="story-ring block">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={story.image}
                alt={`@${story.username}'s story`}
                width={56}
                height={56}
                className="film-bw block h-14 w-14 object-cover"
                style={{ imageRendering: "pixelated" }}
              />
            </span>
            <span className="w-full truncate text-center text-base text-blue-brand">
              {story.username}
            </span>
          </div>
        ))}
      </div>
    </section>
  );
}
